# TODO: support both ansible running from the host or from the guest machines
# k8s config backport from kubespray https://github.com/kubernetes-incubator/kubespray/blob/master/Vagrantfile#L26
teracy-dev-k8s:
  # configurable here
  kubespray:
    lookup_path: workspace # relative to the Vagrantfile
    location:
      git: https://github.com/kubernetes-incubator/kubespray.git
      branch: v2.6.0
  ansible_mode: guest # or host to run ansible from the host instead of from the guest
  num_instances: 1
  instance_name_prefix: "k8s"
  vm_gui: false
  vm_memory: 2048
  vm_cpus: 1
  os: ubuntu # coreos-stable | coreos-alpha | coreos-beta | centos | opensuse | opensuse-tumbleweed
  network_plugin: flannel
  local_release_dir: /vagrant/temp
  network:
    mode: private_network # TODO: support "public_network" with automatic public ip of the master node so it's LAN accessible
    subnet: 172.17.8

  # don't try to change node_template if you don't know what you're going to do
  # node template to be overriden
  node_template:
    _id:
    name: 
    vm:
      box:
      box_version:
      box_url:
      networks:
        - _id: "0"
          mode:
          ip:
    ssh:
      insert_key: false
      username:
    providers:
      - _id: "0"
        gui:
        memory:
        cpus:
        description: "k8s #{Time.now.getutc.to_i}"
    provisioners:
      - _id: "0"
        type: shell
        enabled: true
        inline: swapoff -a
      - _id: "1"
        type: ansible_local
        enabled: true
        playbook: workspace/kubespray/cluster.yml # TODO: use env var of kubespray.lookup_path
        become: true
        limit: all
        raw_arguments:
        host_vars: {}
        verbose: v
        install_mode: pip_args_only
        pip_args: -r /vagrant/workspace/kubespray/requirements.txt
        groups: {}
